package com.bankledger.safegem.greendaodb.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bankledger.safegem.greendaodb.entity.ColdWalletTb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "cold_wallet".
*/
public class ColdWalletTbDao extends AbstractDao<ColdWalletTb, Long> {

    public static final String TABLENAME = "cold_wallet";

    /**
     * Properties of entity ColdWalletTb.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "id");
        public final static Property UserId = new Property(1, Long.class, "userId", false, "user_id");
        public final static Property ColdUniqueId = new Property(2, String.class, "coldUniqueId", false, "cold_unique_id");
        public final static Property ColdWalletName = new Property(3, String.class, "coldWalletName", false, "cold_wallet_name");
        public final static Property Date = new Property(4, String.class, "date", false, "data");
    }


    public ColdWalletTbDao(DaoConfig config) {
        super(config);
    }
    
    public ColdWalletTbDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"cold_wallet\" (" + //
                "\"id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"user_id\" INTEGER," + // 1: userId
                "\"cold_unique_id\" TEXT UNIQUE ," + // 2: coldUniqueId
                "\"cold_wallet_name\" TEXT," + // 3: coldWalletName
                "\"data\" TEXT);"); // 4: date
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"cold_wallet\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ColdWalletTb entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long userId = entity.getUserId();
        if (userId != null) {
            stmt.bindLong(2, userId);
        }
 
        String coldUniqueId = entity.getColdUniqueId();
        if (coldUniqueId != null) {
            stmt.bindString(3, coldUniqueId);
        }
 
        String coldWalletName = entity.getColdWalletName();
        if (coldWalletName != null) {
            stmt.bindString(4, coldWalletName);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(5, date);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ColdWalletTb entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long userId = entity.getUserId();
        if (userId != null) {
            stmt.bindLong(2, userId);
        }
 
        String coldUniqueId = entity.getColdUniqueId();
        if (coldUniqueId != null) {
            stmt.bindString(3, coldUniqueId);
        }
 
        String coldWalletName = entity.getColdWalletName();
        if (coldWalletName != null) {
            stmt.bindString(4, coldWalletName);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(5, date);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ColdWalletTb readEntity(Cursor cursor, int offset) {
        ColdWalletTb entity = new ColdWalletTb( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // userId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // coldUniqueId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // coldWalletName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // date
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ColdWalletTb entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setColdUniqueId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setColdWalletName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDate(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ColdWalletTb entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ColdWalletTb entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ColdWalletTb entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
